# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/azureuser/image_recognition

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/azureuser/image_recognition

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/azureuser/image_recognition/CMakeFiles /home/azureuser/image_recognition//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/azureuser/image_recognition/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ImageRecognition

# Build rule for target.
ImageRecognition: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ImageRecognition
.PHONY : ImageRecognition

# fast build rule for target.
ImageRecognition/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition.dir/build.make CMakeFiles/ImageRecognition.dir/build
.PHONY : ImageRecognition/fast

#=============================================================================
# Target rules for targets named create_output_dir

# Build rule for target.
create_output_dir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 create_output_dir
.PHONY : create_output_dir

# fast build rule for target.
create_output_dir/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/create_output_dir.dir/build.make CMakeFiles/create_output_dir.dir/build
.PHONY : create_output_dir/fast

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean-all.dir/build.make CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

#=============================================================================
# Target rules for targets named r

# Build rule for target.
r : cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r
.PHONY : r

# fast build rule for target.
r/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r.dir/build.make CMakeFiles/r.dir/build
.PHONY : r/fast

#=============================================================================
# Target rules for targets named ImageRecognition_test

# Build rule for target.
ImageRecognition_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ImageRecognition_test
.PHONY : ImageRecognition_test

# fast build rule for target.
ImageRecognition_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition_test.dir/build.make CMakeFiles/ImageRecognition_test.dir/build
.PHONY : ImageRecognition_test/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/image.o: src/image.cpp.o
.PHONY : src/image.o

# target to build an object file
src/image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition.dir/build.make CMakeFiles/ImageRecognition.dir/src/image.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition_test.dir/build.make CMakeFiles/ImageRecognition_test.dir/src/image.cpp.o
.PHONY : src/image.cpp.o

src/image.i: src/image.cpp.i
.PHONY : src/image.i

# target to preprocess a source file
src/image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition.dir/build.make CMakeFiles/ImageRecognition.dir/src/image.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition_test.dir/build.make CMakeFiles/ImageRecognition_test.dir/src/image.cpp.i
.PHONY : src/image.cpp.i

src/image.s: src/image.cpp.s
.PHONY : src/image.s

# target to generate assembly for a file
src/image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition.dir/build.make CMakeFiles/ImageRecognition.dir/src/image.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition_test.dir/build.make CMakeFiles/ImageRecognition_test.dir/src/image.cpp.s
.PHONY : src/image.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition.dir/build.make CMakeFiles/ImageRecognition.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition.dir/build.make CMakeFiles/ImageRecognition.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition.dir/build.make CMakeFiles/ImageRecognition.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/opencl_image.o: src/opencl_image.cpp.o
.PHONY : src/opencl_image.o

# target to build an object file
src/opencl_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition.dir/build.make CMakeFiles/ImageRecognition.dir/src/opencl_image.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition_test.dir/build.make CMakeFiles/ImageRecognition_test.dir/src/opencl_image.cpp.o
.PHONY : src/opencl_image.cpp.o

src/opencl_image.i: src/opencl_image.cpp.i
.PHONY : src/opencl_image.i

# target to preprocess a source file
src/opencl_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition.dir/build.make CMakeFiles/ImageRecognition.dir/src/opencl_image.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition_test.dir/build.make CMakeFiles/ImageRecognition_test.dir/src/opencl_image.cpp.i
.PHONY : src/opencl_image.cpp.i

src/opencl_image.s: src/opencl_image.cpp.s
.PHONY : src/opencl_image.s

# target to generate assembly for a file
src/opencl_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition.dir/build.make CMakeFiles/ImageRecognition.dir/src/opencl_image.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition_test.dir/build.make CMakeFiles/ImageRecognition_test.dir/src/opencl_image.cpp.s
.PHONY : src/opencl_image.cpp.s

src/test.o: src/test.cc.o
.PHONY : src/test.o

# target to build an object file
src/test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition_test.dir/build.make CMakeFiles/ImageRecognition_test.dir/src/test.cc.o
.PHONY : src/test.cc.o

src/test.i: src/test.cc.i
.PHONY : src/test.i

# target to preprocess a source file
src/test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition_test.dir/build.make CMakeFiles/ImageRecognition_test.dir/src/test.cc.i
.PHONY : src/test.cc.i

src/test.s: src/test.cc.s
.PHONY : src/test.s

# target to generate assembly for a file
src/test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition_test.dir/build.make CMakeFiles/ImageRecognition_test.dir/src/test.cc.s
.PHONY : src/test.cc.s

src/viola_jones.o: src/viola_jones.cpp.o
.PHONY : src/viola_jones.o

# target to build an object file
src/viola_jones.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition.dir/build.make CMakeFiles/ImageRecognition.dir/src/viola_jones.cpp.o
.PHONY : src/viola_jones.cpp.o

src/viola_jones.i: src/viola_jones.cpp.i
.PHONY : src/viola_jones.i

# target to preprocess a source file
src/viola_jones.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition.dir/build.make CMakeFiles/ImageRecognition.dir/src/viola_jones.cpp.i
.PHONY : src/viola_jones.cpp.i

src/viola_jones.s: src/viola_jones.cpp.s
.PHONY : src/viola_jones.s

# target to generate assembly for a file
src/viola_jones.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageRecognition.dir/build.make CMakeFiles/ImageRecognition.dir/src/viola_jones.cpp.s
.PHONY : src/viola_jones.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... clean-all"
	@echo "... create_output_dir"
	@echo "... r"
	@echo "... ImageRecognition"
	@echo "... ImageRecognition_test"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... src/image.o"
	@echo "... src/image.i"
	@echo "... src/image.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/opencl_image.o"
	@echo "... src/opencl_image.i"
	@echo "... src/opencl_image.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
	@echo "... src/viola_jones.o"
	@echo "... src/viola_jones.i"
	@echo "... src/viola_jones.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

